### model
model_name_or_path: /home/models/Qwen/Qwen2.5-14B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all  # lora所有模块
# deepspeed: /root/LLaMA-Factory/examples/deepspeed/ds_z3_offload_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: train_sft_llm_detect_mask_aug_14B_v8
template: qwen
cutoff_len: 1800  # 截断最大长度
max_samples: 1000000000  # 每个dataset的最大长度
overwrite_cache: true
preprocessing_num_workers: 16


### output
output_dir: /home/jovyan/cjn/trained_model/Qwen2.5-14B-lora0622-v2.7
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 5.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: False
ddp_timeout: 180000000  # 并行通信的超时限制

max_grad_norm: 1.0  # 梯度裁剪阈值
warmup_steps: 24  # 学习率预热步数
packing: False  # 将不同长度的进行打包
flash_attn: auto
lora_rank: 256
lora_alpha: 256
lora_dropout: 0.1
torch_empty_cache_steps: 4
resume_from_checkpoint: True
### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500

